football_schedule/football_schedule/programs/urls.py
from django.urls import path, include

from football_schedule.programs.views import CreateMatchView, DeleteAllMatchesView, delete_match, EditMatchView, \
    DisplayProgramView

urlpatterns = [
    path('create/', CreateMatchView.as_view(), name='create-program'),
    path('display/', DisplayProgramView.as_view(), name='display-program'),
    path('delete-all-matches/', DeleteAllMatchesView.as_view(), name='delete-all-matches'),
    path('match/<int:pk>/',include([
        path('delete/', delete_match, name='delete-match'),
        path('edit/', EditMatchView.as_view(), name='edit-match')
    ])),

]

football_schedule/football_schedule/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('football_schedule.common.urls')),
    path('accounts/', include('football_schedule.accounts.urls')),
    path('schedule/', include('football_schedule.schedules.urls')),
    path('program/', include('football_schedule.programs.urls')),
    path('report/', include('football_schedule.reports.urls')),
]

football_schedule/football_schedule/programs/models.py
from cloudinary.models import CloudinaryField
from django.contrib.auth import get_user_model
from django.db import models

UserModel = get_user_model()

# Create your models here.

class Match(models.Model):
    author = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='matches',
    )

    team_1 = models.CharField(
        max_length=50
    )

    use_team_1_profile_emblem = models.BooleanField(
        default=False
    )

    team_1_emblem = CloudinaryField(
        'club_emblem',
        folder='programs',
        null=True,
        blank=True,
    )

    team_2 = models.CharField(
        max_length=50
    )

    use_team_2_profile_emblem = models.BooleanField(
        default=False
    )

    team_2_emblem = CloudinaryField(
        'club_emblem',
        folder='programs',
        null=True,
        blank=True,
    )

    date = models.DateField()

    time = models.TimeField()

    place = models.CharField(
        max_length=100,
    )


class DisplayProgramData(models.Model):
    user=models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
        related_name='display_program'
    )

    club = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )

    club_emblem = CloudinaryField(
    'club_emblem',
        folder='accounts',
        null=True,
        blank=True,
    )

    use_emblems = models.BooleanField(
        default=True
    )

football_schedule/football_schedule/programs/forms.py
from django import forms

from football_schedule.programs.models import Match, DisplayProgramData


class MatchBaseForm(forms.ModelForm):
    class Meta:
        model = Match
        exclude = ('author',)
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date', 'class': 'form-control'}),
            'time': forms.TimeInput(attrs={'type': 'time', 'class': 'form-control'}),
        }
        labels = {
            'team_1': 'Отбор',
            'use_team_1_profile_emblem': 'Използвай клубна емблема',
            'team_1_emblem': 'Отбор Емблема',
            'team_2': 'Противник',
            'use_team_2_profile_emblem': 'Използвай клубна емблема',
            'team_2_emblem': 'Противник Емблема',
            'date': 'Дата',
            'time': 'Час',
            'place': 'Място',

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs.update({
                'class': 'wide-input-small'
            })

class MatchCreateForm(MatchBaseForm):
    pass


class MatchEditForm(MatchBaseForm):
    pass

class DisplayProgramForm(forms.ModelForm):
    class Meta:
        model = DisplayProgramData
        exclude = ('user',)

football_schedule/football_schedule/programs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib import messages
from django.views import View
from django.views.generic import UpdateView, ListView
from football_schedule.programs.forms import MatchCreateForm, MatchEditForm, DisplayProgramForm
from football_schedule.programs.models import Match, DisplayProgramData


class CreateMatchView(LoginRequiredMixin, View):
    template_name = 'programs/create-program.html'
    success_url = reverse_lazy('create-program')

    def get_user_profile_data(self):

        user_profile = getattr(self.request.user, 'profile', None)
        return {
            'club': user_profile.club if user_profile else '',
            'club_emblem': user_profile.club_emblem if user_profile and user_profile.club_emblem else None,
        }

    def get_context_data(self, **kwargs):

        context = kwargs
        context.setdefault('form', kwargs.get('form', MatchCreateForm()))
        context.setdefault('display_program_form', DisplayProgramForm(initial=self.get_user_profile_data()))
        context['matches'] = Match.objects.filter(author=self.request.user).order_by('date', 'time')

        return context

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, self.get_context_data())

    def post(self, request, *args, **kwargs):
        form_type = request.POST.get("form_type")

        if form_type == "match_form":
            match_form = MatchCreateForm(request.POST, request.FILES)

            if match_form.is_valid():
                match = match_form.save(commit=False)
                match.author = request.user

                profile = getattr(request.user, 'profile', None)

                if match.use_team_1_profile_emblem and profile:
                    match.team_1_emblem = profile.club_emblem

                if match.use_team_2_profile_emblem and profile:
                    match.team_2_emblem = profile.club_emblem

                match.save()
                return redirect(self.success_url)

            return render(request, self.template_name, self.get_context_data(form=match_form))

        elif form_type == "display_program_form":
            display_program_form = DisplayProgramForm(request.POST, request.FILES)

            if display_program_form.is_valid():
                display_program = display_program_form.save(commit=False)
                display_program.user = request.user

                if "club_emblem-clear" in request.POST:
                    display_program.club_emblem = None
                elif not request.FILES.get("club_emblem"):
                    user_profile = getattr(request.user, 'profile', None)
                    if user_profile:
                        display_program.club_emblem = user_profile.club_emblem
                display_program.save()
                return redirect(reverse_lazy('display-program'))

            return render(request, self.template_name, self.get_context_data(display_program_form=display_program_form))

        return redirect(self.success_url)


class EditMatchView(LoginRequiredMixin, UpdateView):
    template_name = 'programs/edit-match.html'
    form_class = MatchEditForm
    model = Match
    success_url = reverse_lazy('create-program')

    def dispatch(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.author and not self.request.user.is_superuser:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        match = form.save(commit=False)
        profile = getattr(self.request.user, 'profile', None)

        if match.use_team_1_profile_emblem and profile:
            match.team_1_emblem = profile.club_emblem

        if match.use_team_2_profile_emblem and profile:
            match.team_2_emblem = profile.club_emblem

        match.save()
        return super().form_valid(form)

class DeleteAllMatchesView(View):
    def post(self, request, *args, **kwargs):

        matches_deleted, _ = Match.objects.filter(author=request.user).delete()
        messages.success(request, f"Successfully deleted {matches_deleted} matches.")

        return redirect('create-program')

def delete_match(request, pk):

    match = get_object_or_404(Match, pk=pk, author=request.user)
    match.delete()

    return redirect('create-program')

class DisplayProgramView(LoginRequiredMixin,ListView):
    template_name = 'programs/display-program.html'
    model = Match

    def get_queryset(self):
        queryset = Match.objects.filter(author=self.request.user).order_by('date','time')
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        if DisplayProgramData.objects.filter(user_id=self.request.user.id).count() > 1:
            DisplayProgramData.objects.first().delete()

        dates = []
        matches = Match.objects.filter(author=self.request.user).order_by('date','time')
        for match in matches:
            if match.date not in dates:
                dates.append(match.date)

        first_date = dates[0]
        last_date = dates[-1] if len(dates) > 1 else None

        context['dates'] = dates
        context['display_program_data'] = DisplayProgramData.objects.filter(user_id=self.request.user.id).first()
        context['first_date'] = first_date
        context['last_date'] = last_date

        return context

football_schedule/templates/programs/create-match.html
<section id="create-schedule" class="p-2 m-5">
    <h2 class="text-center">Създай мач</h2>
    <form id="create-schedule-form" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="form_type" value="match_form">  <!-- Hidden field to identify form -->

        <h3 class="text-center py-2">Отбор</h3>
        <div id="monday" class="pb-3">
            <p class="text-center">{{ form.team_1.label }}<br>{{ form.team_1 }}</p>
            <p class="text-center">{{ form.team_1_emblem.label }}<br>{{ form.team_1_emblem }}</p>
            <p class="text-center">{{ form.use_team_1_profile_emblem.label }}<br>{{ form.use_team_1_profile_emblem }}
            </p>
        </div>

        <h3 class="text-center pb-2">Противник</h3>
        <div id="monday" class="pb-3">
            <p class="text-center">{{ form.team_2.label }}<br>{{ form.team_2 }}</p>
            <p class="text-center">{{ form.team_2_emblem.label }}<br>{{ form.team_2_emblem }}</p>
            <p class="text-center">{{ form.use_team_2_profile_emblem.label }}<br>{{ form.use_team_2_profile_emblem }}
            </p>
        </div>

        <h3 class="text-center pb-2">Информация</h3>
        <div id="monday" class="pb-3">
            <p class="text-center">{{ form.date.label }}<br>{{ form.date }}</p>
            <p class="text-center">{{ form.time.label }}<br>{{ form.time }}</p>
            <p class="text-center">{{ form.place.label }}<br>{{ form.place }}</p>
        </div>

        <div class="d-flex justify-content-center">
            <button type="submit" class="btn px-5 py-2 btn-primary text-center">Създай мач</button>
        </div>
    </form>
</section>

football_schedule/templates/programs/create-program.html
{% extends 'base.html' %}


{% block content %}
    {% include 'head.html' with bootstrap=True %}
    

    <div class="d-flex flex-column justify-content-center align-items-center">

        {% include 'programs/create-match.html' %}
    
        {% include 'programs/matches.html' %}
        
        {% include 'programs/form-program.html' %}
    
    </div>

{% endblock %}

football_schedule/templates/programs/display-program-matches-emblems.html
{% load static %}
<div id="matches">
    {% for date in dates %}
        <h3 class="date-header">{{ date|date:"l d F"|default:"" }}</h3>
        <table id="program">
            <thead>
            <tr>
            </tr>
            </thead>
            <tbody>
            {% for match in match_list %}
                {% if match.date == date %}
                    <tr>
                        <td class="no-bold-text no-text-colapse">{{ match.time|time:"H:i" }}</td>
                        {% if match.team_1_emblem %}
                            <td><img class="program-emblem" src="{{ match.team_1_emblem.url }}"></td>
                        {% else %}
                            <td><img class="program-emblem" src="{% static 'images/default-emblem.png' %}">
                            </td>
                        {% endif %}
                        <td class="team-name">{{ match.team_1 }}</td>
                        <td id="small">-</td>
                        <td class="team-name">{{ match.team_2 }}</td>
                        {% if match.team_2_emblem %}
                            <td><img class="program-emblem" src="{{ match.team_2_emblem.url }}"></td>
                        {% else %}
                            <td><img class="program-emblem" src="{% static 'images/default-emblem.png' %}">
                            </td>
                        {% endif %}
                        <td class="no-bold-text">{{ match.place }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    {% endfor %}
</div>

football_schedule/templates/programs/display-program-matches-no-emblems.html
{% load static %}
<div id="matches">
    {% for date in dates %}
        <h3 class="date-header">{{ date|date:"l d F"|default:"" }}</h3>
        <table id="program">
            <thead>
            <tr>
            </tr>
            </thead>
            <tbody>
            {% for match in match_list %}
                {% if match.date == date %}
                    <tr>
                        <td class="no-bold-text no-text-colapse">{{ match.time|time:"H:i" }}</td>
                        <td class="team-name">{{ match.team_1 }}</td>
                        <td id="small">-</td>
                        <td class="team-name">{{ match.team_2 }}</td>
                        <td class="no-bold-text">{{ match.place }}</td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    {% endfor %}
</div>

football_schedule/templates/programs/display-program-old.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'head.html' with bootstrap=False %}

    <div id="display-page">
        <button id="download-screenshot">Свали програма (.jpg)</button>
    </div>
    
<section id="program" class="p-2 m-5">
    <div id="program-image">
    
        <div class="program-info">
            <div class="">
                <img id="create-program-emblem" src="{{ display_program_data.club_emblem.url }}">
                
            </div>
            
            <div>
                <h3>{{ display_program_data.club}}</h3>
                <h3>Програма мачове</h3>
                {% if last_date %}
                    <h3>{{ first_date|date:'d.m' }} - {{ last_date|date:'d.m' }}</h3>
                {% endif %}
            </div>
            
        </div>
        
        <div id="matches">
            {% for date in dates %}
                <h3 class="date-header">{{ date|date:"l d F"|default:"" }}</h3>
                <table id="program">
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tbody>
                        {% for match in match_list %}
                            {% if match.date == date %}
                                <tr >
                                    <td>{{ match.time|time:"H:i" }} часа</td>
                                    {% if match.team_1_emblem %}
                                        <td><img class="program-emblem" src="{{ match.team_1_emblem.url }}"></td>
                                    {% else %}
                                        <td><img class="program-emblem" src="{% static 'images/default-emblem.png' %}"></td>
                                    {% endif %}
                                    <td>{{ match.team_1 }}</td>
                                    <td id="small">-</td>
                                    <td>{{ match.team_2 }}</td>
                                    {% if match.team_2_emblem %}
                                        <td><img class="program-emblem" src="{{ match.team_2_emblem.url }}"></td>
                                    {% else %}
                                        <td><img class="program-emblem" src="{% static 'images/default-emblem.png' %}"></td>
                                    {% endif %}
                                    <td>{{ match.place }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            {% endfor %}
        </div>
    </div>
</section>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
    
<script>
document.getElementById("download-screenshot").addEventListener("click", function () {
    let section = document.getElementById("program-image"); // The section we want to capture

    // Capture the entire section exactly as it appears on the screen
    html2canvas(section, { 
        backgroundColor: null,  // Avoid default black background
        scale: 2,               // Higher scale for better quality
        useCORS: true,          // Allow cross-origin resources (like images)
        logging: false,         // Disable logging for cleaner code
        scrollX: 0,             // No scrolling offsets
        scrollY: 0,             // No scrolling offsets
    }).then(canvas => {
        // Get the original width and height of the captured content
        let originalWidth = canvas.width;
        let originalHeight = canvas.height;

        // Define how much to crop from the left and right (200px from each side)
        let cropMargin = 750; // 200px from the left and right
        let newWidth = originalWidth - (2 * cropMargin); // Crop from both sides
        let newHeight = originalHeight; // Height remains the same

        // Create a new canvas for the cropped content
        let croppedCanvas = document.createElement("canvas");
        croppedCanvas.width = newWidth;
        croppedCanvas.height = newHeight;
        let ctx = croppedCanvas.getContext("2d");

        // Draw the cropped section onto the new canvas (skip the left and right margins)
        ctx.drawImage(canvas, cropMargin, 0, newWidth, newHeight, 0, 0, newWidth, newHeight);

        // Convert cropped canvas to JPG format
        let link = document.createElement("a");
        link.href = croppedCanvas.toDataURL("image/jpeg", 0.95); // 95% JPG quality
        link.download = "program.jpg"; // The downloaded file name
        link.click(); // Trigger the download
    });
});
</script>






{% endblock %}

football_schedule/templates/programs/display-program.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% include 'head.html' with bootstrap=False %}

    <div id="display-page">
        <button id="download-screenshot">Свали програма (.jpg)</button>
    </div>
    <!-- Div to capture -->
    <div id="to-screenshot">
        <section id="display-page-section">
            <!-- Your section content here -->
            <div class="program-info">
                <div class="">
                    <img id="display-program-emblem" src="{{ display_program_data.club_emblem.url }}">
                </div>

                <div class="program-info-text">
                    <h3 style="font-size: 3rem; margin:  0.5rem 0">{{ display_program_data.club }}</h3>
                    <h3 style="font-size: 2rem; margin:  0.5rem 0">Програма мачове</h3>
                    {% if last_date %}
                        <h3 style="font-size: 2rem; margin: 0.5rem 0">{{ first_date|date:'d.m' }}
                            - {{ last_date|date:'d.m' }}</h3>
                    {% endif %}
                </div>
            </div>



            {% if display_program_data.use_emblems %}
                {% include 'programs/display-program-matches-emblems.html' %}
            {% else %}
                {% include 'programs/display-program-matches-no-emblems.html' %}
            {% endif %}

        </section>
    </div>
    </div>


    <!-- Include html2canvas -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>

    <!-- JavaScript to handle the screenshot -->

    <script>
        window.onload = function () {
            document.getElementById("download-screenshot").addEventListener("click", function () {
                const elementToCapture = document.getElementById("to-screenshot");

                // Capture the element using html2canvas
                html2canvas(elementToCapture, {
                    backgroundColor: "#ECEBDE", // Set the background color
                    useCORS: true, // Enable CORS for external images
                }).then(function (canvas) {
                    // Create a new canvas for the full image (no cropping)
                    const fullCanvas = document.createElement("canvas");
                    fullCanvas.width = canvas.width;
                    fullCanvas.height = canvas.height;

                    const ctx = fullCanvas.getContext("2d");

                    // Draw the full canvas (no cropping)
                    ctx.drawImage(
                        canvas, // Source canvas
                        0, // Start from the left edge (no cropping)
                        0, // Start from the top edge (no cropping)
                        canvas.width, // Full width of the original canvas
                        canvas.height, // Full height of the original canvas
                        0, // Destination x
                        0, // Destination y
                        canvas.width, // Destination width
                        canvas.height // Destination height
                    );

                    // Convert the full canvas to an image
                    const imageData = fullCanvas.toDataURL("image/jpeg", 1.0); // Save as JPEG
                    const link = document.createElement("a");
                    link.href = imageData;
                    link.download = "football-program.jpg"; // Use .jpg extension
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                });
            });
        };


    </script>
{% endblock %}

    

football_schedule/templates/programs/edit-match.html
{% extends 'base.html' %}


{% block content %}
    {% include 'head.html' with bootstrap=True %}
    
    <div class="d-flex flex-column justify-content-center align-items-center">
    <section id="create-schedule" class=" p-2 m-5">
            <h2 class="text-center"> Редактирай мач</h2>
            <form id="create-schedule-form" method="post">
                {% csrf_token %}
                <h3 class="text-center"></h3>

                <h3 class="text-center py-2">Отбор</h3>
        <div id="monday" class="pb-3">
            <p class="text-center">{{ form.team_1.label }}<br>{{ form.team_1 }}</p>
            <p class="text-center">{{ form.team_1_emblem.label }}<br>{{ form.team_1_emblem }}</p>
            <p class="text-center">{{ form.use_team_1_profile_emblem.label }}<br>{{ form.use_team_1_profile_emblem }}
            </p>
        </div>

        <h3 class="text-center pb-2">Противник</h3>
        <div id="monday" class="pb-3">
            <p class="text-center">{{ form.team_2.label }}<br>{{ form.team_2 }}</p>
            <p class="text-center">{{ form.team_2_emblem.label }}<br>{{ form.team_2_emblem }}</p>
            <p class="text-center">{{ form.use_team_2_profile_emblem.label }}<br>{{ form.use_team_2_profile_emblem }}
            </p>
        </div>

        <h3 class="text-center pb-2">Информация</h3>
        <div id="monday" class="pb-3">
            <p class="text-center">{{ form.date.label }}<br>{{ form.date }}</p>
            <p class="text-center">{{ form.time.label }}<br>{{ form.time }}</p>
            <p class="text-center">{{ form.place.label }}<br>{{ form.place }}</p>
        </div>

                <div class="d-flex justify-content-center">
                    <button type="submit" name="submit_form" class="btn px-5 py-2  btn-primary text-center">Редактирай мач
                    </button>
                </div>

            </form>
        </section>
    </div>

{% endblock %}

football_schedule/templates/programs/form-program.html
<section id="create-schedule" class="p-2 m-5">
    <h2 class="text-center">Създай Програма</h2>
    <form id="create-schedule-form" method="post" enctype="multipart/form-data" action="">
        {% csrf_token %}
         <input type="hidden" name="form_type" value="display_program_form">  <!-- Hidden field to identify form -->
        
        <h3 class="text-center py-2">Отбор</h3>
        <div class="text-center">
            {{ display_program_form.club }}
        </div>

        <h3 class="text-center py-2">Емблема</h3>
        <p class="text-center" style="font-style: italic; font-weight: inherit">Ако не добавите клубна емблема от полето по-долу ще бъде използвана тази снимка</p>
        <div class="text-center">
            <img id="form-program-club-emblem" src="{{ display_program_form.initial.club_emblem.url }}"> 
        </div>
        <div class="text-center">
            {{ display_program_form.club_emblem }}
        </div>
        
        <div class="text-center">
            <h3 class="text-center py-2">Използвай емблеми на отборите в програмата</h3>
            <p class="text-center" style="font-size: 1.5rem">Използвай емблеми  {{ display_program_form.use_emblems}}</p>
        </div>

        <div class="d-flex justify-content-center">
            <button type="submit" class="btn px-3 py-3 btn-primary text-center bg-primary">Създай Програма</button>
        </div>
    </form>
</section>

football_schedule/templates/programs/matches.html
<section id="weeks" class="p-2 m-5">

    <div>
        <h2 class="text-center">Създадени Мачове</h2>
    </div>

    <div class="d-flex justify-content-around">

        {% if matches %}
            <ul>
                {% for match in matches %}
                    <div class="d-flex justify-content-between">
                        <li>
                            <div class="pr-4 mr-3">
                                {{ match.team_1 }} - {{ match.team_2 }}
                            </div>
                            <div class="pr-4 mr-3">
                                {{ match.date|date:"d.m.Y" }} {{ match.time|time:"H:i" }}
                            </div>
                            <div class="pr-4 mr-3">
                                {{ match.place }}
                            </div>
                            <div>
                                <div class="weeks-li-a">
                                    <a class="week-a" href="{% url 'edit-match' match.pk %}">
                                        <i class="fa-solid fa-pen"></i>редактирай
                                    </a>
                                    <a class="week-delete" href="{% url 'delete-match' match.pk %}"
                                       onclick="return confirm('Сигурен ли си, че искаш да изтриеш тази мач?');">
                                        <i class="fa-solid fa-trash"></i>изтрий
                                    </a>
                                </div>
                            </div>
                        </li>
                    </div>
                {% endfor %}
            </ul>
        {% else %}
            <h2 id="no-weeks"> Все още няма създадени мачове</h2>
        {% endif %}

    </div>


    <form class="px-5 d-flex align-items-center justify-content-center" method="post"
          action="{% url 'delete-all-matches' %}" onsubmit="return confirmDelete()">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger px-3 py-3">Изтрий всички мачове</button>
    </form>


</section>

<script>
    function confirmDelete() {
        return confirm("Сигурен ли си, че искаш да изтриеш всички създадени мачове?");
    }
</script>